#!/bin/bash
echo  "Updating IZING, please wait."
cd  ~
cd izing.io
git checkout master
git pull
cd backend
bun install
rm -rf dist
bun run build
bunx sequelize db:migrate
#bunx sequelize db:seed
pm2 restart all

echo  "Update finished. Enjoy!"
